name: demo

on:
  schedule:
    - cron: '10,20,30,40,50,00 * * * 1,2,3,4,5'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo `date`
          curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=ad22a2c7-e205-494f-9c42-3caadad42840' -H 'Content-Type: application/json' -d '{"msgtype": "text","text": {"content": "ccc!"} }'
